# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RndrApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for RndrApp

  target 'RndrAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RndrAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


